<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

	'punch-ball (box set)' => $set . '_e900',
	'scale (box set)' => $set . '_e901',
	'smartphone (box set)' => $set . '_e902',
	'shoes (box set)' => $set . '_e903',
	'boxer (box set)' => $set . '_e904',
	'gong (box set)' => $set . '_e905',
	'helmet (box set)' => $set . '_e906',
	'video (box set)' => $set . '_e907',
	'punch-ball1 (box set)' => $set . '_e908',
	'boxing-gloves (box set)' => $set . '_e909',
	'boxing (box set)' => $set . '_e90a',
	'round (box set)' => $set . '_e90b',
	'tape (box set)' => $set . '_e90c',
	'clipboard (box set)' => $set . '_e90d',
	'punch (box set)' => $set . '_e90e',
	'water-bottle (box set)' => $set . '_e90f',
	'boxing-glove (box set)' => $set . '_e910',
	'punch1 (box set)' => $set . '_e911',
	'ring (box set)' => $set . '_e912',
	'fist (box set)' => $set . '_e913',
	'Bet (box set)' => $set . '_e914',
	'fight (box set)' => $set . '_e915',
	'skipping-rope (box set)' => $set . '_e916',
	'boxing1 (box set)' => $set . '_e917',
	'shorts (box set)' => $set . '_e918',
	'helmet1 (box set)' => $set . '_e919',
	'dummy (box set)' => $set . '_e91a',
	'placeholder (box set)' => $set . '_e91b',
	'pad (box set)' => $set . '_e91c',
	'shield (box set)' => $set . '_e91d',
	'referee (box set)' => $set . '_e91e',
	'calendar (box set)' => $set . '_e91f',
	'duffle-bag (box set)' => $set . '_e920',
	'punch-ball2 (box set)' => $set . '_e921',
	'muscle (box set)' => $set . '_e922',
	'boxing2 (box set)' => $set . '_e923',
	'kettlebell (box set)' => $set . '_e924',
	'bell (box set)' => $set . '_e925',
	'gum-shield (box set)' => $set . '_e926',
	'boxing3 (box set)' => $set . '_e927',
	'boxing4 (box set)' => $set . '_e928',
	'ticket (box set)' => $set . '_e929',
	'robe (box set)' => $set . '_e92a',
	'boxing5 (box set)' => $set . '_e92b',
	'belt (box set)' => $set . '_e92c',
	'protector (box set)' => $set . '_e92d',
	'trophy (box set)' => $set . '_e92e',
	'punch-ball3 (box set)' => $set . '_e92f',
	'winner (box set)' => $set . '_e930',
	'chat (box set)' => $set . '_e931'
);
