<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

	'coin-toss (soccer set)' => $set . '_e900',
	'avatar (soccer set)' => $set . '_e901',
	'monitor (soccer set)' => $set . '_e902',
	'equipment (soccer set)' => $set . '_e903',
	'bottle (soccer set)' => $set . '_e904',
	'entertainment (soccer set)' => $set . '_e905',
	'Aerosol (soccer set)' => $set . '_e906',
	'music (soccer set)' => $set . '_e907',
	'administration (soccer set)' => $set . '_e908',
	'architecture-and-city (soccer set)' => $set . '_e909',
	'competition (soccer set)' => $set . '_e90a',
	'avatar1 (soccer set)' => $set . '_e90b',
	'award (soccer set)' => $set . '_e90c',
	'card (soccer set)' => $set . '_e90d',
	'architecture-and-city1 (soccer set)' => $set . '_e90e',
	'arrows (soccer set)' => $set . '_e90f',
	'award1 (soccer set)' => $set . '_e910',
	'bag (soccer set)' => $set . '_e911',
	'ball (soccer set)' => $set . '_e912',
	'card1 (soccer set)' => $set . '_e913',
	'badge (soccer set)' => $set . '_e914',
	'ball1 (soccer set)' => $set . '_e915',
	'clothes (soccer set)' => $set . '_e916',
	'bracelet (soccer set)' => $set . '_e917',
	'farming-and-gardening (soccer set)' => $set . '_e918',
	'christmas (soccer set)' => $set . '_e919',
	'basketball (soccer set)' => $set . '_e91a',
	'analysis (soccer set)' => $set . '_e91b',
	'electronics (soccer set)' => $set . '_e91c',
	'doctor (soccer set)' => $set . '_e91d',
	'emergencies (soccer set)' => $set . '_e91e',
	'bollards (soccer set)' => $set . '_e91f',
	'clothing (soccer set)' => $set . '_e920',
	'award2 (soccer set)' => $set . '_e921',
	'award3 (soccer set)' => $set . '_e922',
	'clothes1 (soccer set)' => $set . '_e923',
	'angle (soccer set)' => $set . '_e924',
	'buildings (soccer set)' => $set . '_e925',
	'country (soccer set)' => $set . '_e926',
	'basketball1 (soccer set)' => $set . '_e927',
	'cellphone (soccer set)' => $set . '_e928',
	'announcer (soccer set)' => $set . '_e929',
	'clothing1 (soccer set)' => $set . '_e92a',
	'award4 (soccer set)' => $set . '_e92b',
	'award5 (soccer set)' => $set . '_e92c',
	'chronometer (soccer set)' => $set . '_e92d',
	'football (soccer set)' => $set . '_e92e',
	'football1 (soccer set)' => $set . '_e92f',
	'field (soccer set)' => $set . '_e930',
	'ball2 (soccer set)' => $set . '_e931'
);
