<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(
	'boxing-glove (boxing set)' => $set . '_e900',
	'boxing-ring (boxing set)' => $set . '_e901',
	'boxing-helmet (boxing set)' => $set . '_e902',
	'round (boxing set)' => $set . '_e903',
	'gong (boxing set)' => $set . '_e904',
	'punching-bag (boxing set)' => $set . '_e905',
	'punching-bag1 (boxing set)' => $set . '_e906',
	'dummy (boxing set)' => $set . '_e907',
	'punching-bag2 (boxing set)' => $set . '_e908',
	'punching-bag3 (boxing set)' => $set . '_e909',
	'punching-bag4 (boxing set)' => $set . '_e90a',
	'boxing-shorts (boxing set)' => $set . '_e90b',
	'champion-belt (boxing set)' => $set . '_e90c',
	'boot (boxing set)' => $set . '_e90d',
	'tv (boxing set)' => $set . '_e90e',
	'sport-bag (boxing set)' => $set . '_e90f',
	'signboard (boxing set)' => $set . '_e910',
	'water-bottle (boxing set)' => $set . '_e911',
	'vest (boxing set)' => $set . '_e912',
	'crop-top (boxing set)' => $set . '_e913',
	'focus-mitt (boxing set)' => $set . '_e914',
	'scale (boxing set)' => $set . '_e915',
	'robe (boxing set)' => $set . '_e916',
	'boxing-gloves (boxing set)' => $set . '_e917',
	'shin-guards (boxing set)' => $set . '_e918',
	'protector (boxing set)' => $set . '_e919',
	'mouth-guard (boxing set)' => $set . '_e91a',
	'skipping-rope (boxing set)' => $set . '_e91b',
	'first-aid-kit (boxing set)' => $set . '_e91c',
	'calendar (boxing set)' => $set . '_e91d',
	'bandage (boxing set)' => $set . '_e91e',
	'ticket (boxing set)' => $set . '_e91f',
	'referee (boxing set)' => $set . '_e920',
	'boxing-gloves1 (boxing set)' => $set . '_e921',
	'socks (boxing set)' => $set . '_e922',
	'groin-guard (boxing set)' => $set . '_e923',
	'Paddles (boxing set)' => $set . '_e924',
	'trophy (boxing set)' => $set . '_e925',
	'dumbbell (boxing set)' => $set . '_e926',
	'placeholder (boxing set)' => $set . '_e927'
);
