<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

	'ball (volleyball set)' => $set . '_e900',
	'net (volleyball set)' => $set . '_e901',
	'volleyball (volleyball set)' => $set . '_e902',
	'alignment (volleyball set)' => $set . '_e903',
	'podium (volleyball set)' => $set . '_e904',
	'flag (volleyball set)' => $set . '_e905',
	'medal (volleyball set)' => $set . '_e906',
	'whistle (volleyball set)' => $set . '_e907',
	'hands (volleyball set)' => $set . '_e908',
	'tactic (volleyball set)' => $set . '_e909',
	'hit (volleyball set)' => $set . '_e90a',
	'assistant (volleyball set)' => $set . '_e90b',
	'point (volleyball set)' => $set . '_e90c',
	'water (volleyball set)' => $set . '_e90d',
	'red-card (volleyball set)' => $set . '_e90e',
	'disqualified (volleyball set)' => $set . '_e90f',
	'bench (volleyball set)' => $set . '_e910',
	'calendar (volleyball set)' => $set . '_e911',
	'hit1 (volleyball set)' => $set . '_e912',
	'elbow-pads (volleyball set)' => $set . '_e913',
	'trophy (volleyball set)' => $set . '_e914',
	'isotonic (volleyball set)' => $set . '_e915',
	'ticket (volleyball set)' => $set . '_e916',
	'tier (volleyball set)' => $set . '_e917',
	'beach-volleyball (volleyball set)' => $set . '_e918',
	'rotation (volleyball set)' => $set . '_e919',
	'player (volleyball set)' => $set . '_e91a',
	'player1 (volleyball set)' => $set . '_e91b',
	'equipment (volleyball set)' => $set . '_e91c',
	'score (volleyball set)' => $set . '_e91d',
	'sport-bag (volleyball set)' => $set . '_e91e',
	'shield (volleyball set)' => $set . '_e91f',
	'referee (volleyball set)' => $set . '_e920',
	'first-aid-kit (volleyball set)' => $set . '_e921',
	'knee-pad (volleyball set)' => $set . '_e922',
	'location (volleyball set)' => $set . '_e923',
	'stadium (volleyball set)' => $set . '_e924',
	'antennas (volleyball set)' => $set . '_e925',
	'libero (volleyball set)' => $set . '_e926',
	'injuries (volleyball set)' => $set . '_e927',
	'bandage (volleyball set)' => $set . '_e928',
	'card (volleyball set)' => $set . '_e929',
	'lockers (volleyball set)' => $set . '_e92a',
	'referee1 (volleyball set)' => $set . '_e92b',
	'change (volleyball set)' => $set . '_e92c',
	'bond (volleyball set)' => $set . '_e92d',
	'supporter (volleyball set)' => $set . '_e92e',
	'hit2 (volleyball set)' => $set . '_e92f',
	'chronometer (volleyball set)' => $set . '_e930',
	'mask (volleyball set)' => $set . '_e931'
);
