<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

	'american-football (americanfootball set)' => $set . '_e900',
	'stadium (americanfootball set)' => $set . '_e901',
	'locker (americanfootball set)' => $set . '_e902',
	'helmet (americanfootball set)' => $set . '_e903',
	'down-indicator (americanfootball set)' => $set . '_e904',
	'cleats (americanfootball set)' => $set . '_e905',
	'hot-dog (americanfootball set)' => $set . '_e906',
	'whistle (americanfootball set)' => $set . '_e907',
	'ball (americanfootball set)' => $set . '_e908',
	'ticket (americanfootball set)' => $set . '_e909',
	'free-kick (americanfootball set)' => $set . '_e90a',
	'stretcher (americanfootball set)' => $set . '_e90b',
	'cone (americanfootball set)' => $set . '_e90c',
	'field (americanfootball set)' => $set . '_e90d',
	'soda (americanfootball set)' => $set . '_e90e',
	'sports-and-competition (americanfootball set)' => $set . '_e90f',
	'vip-pass (americanfootball set)' => $set . '_e910',
	'strategy (americanfootball set)' => $set . '_e911',
	'water-bottle (americanfootball set)' => $set . '_e912',
	'mouth-guard (americanfootball set)' => $set . '_e913',
	'down-indicator1 (americanfootball set)' => $set . '_e914',
	'stopwatch (americanfootball set)' => $set . '_e915',
	'goal-post (americanfootball set)' => $set . '_e916',
	'bench (americanfootball set)' => $set . '_e917',
	'location (americanfootball set)' => $set . '_e918',
	'horn (americanfootball set)' => $set . '_e919',
	'ball1 (americanfootball set)' => $set . '_e91a',
	'first-aid-kit (americanfootball set)' => $set . '_e91b',
	'dumbbell (americanfootball set)' => $set . '_e91c',
	't-shirt (americanfootball set)' => $set . '_e91d',
	'goal (americanfootball set)' => $set . '_e91e',
	'short (americanfootball set)' => $set . '_e91f',
	'finger (americanfootball set)' => $set . '_e920',
	'pennant (americanfootball set)' => $set . '_e921',
	'flag (americanfootball set)' => $set . '_e922',
	'referee (americanfootball set)' => $set . '_e923',
	'training (americanfootball set)' => $set . '_e924',
	'broken (americanfootball set)' => $set . '_e925',
	'trophy (americanfootball set)' => $set . '_e926',
	'shoulder (americanfootball set)' => $set . '_e927',
	'down-indicator2 (americanfootball set)' => $set . '_e928',
	'pom-pom (americanfootball set)' => $set . '_e929',
	'flag1 (americanfootball set)' => $set . '_e92a',
	'kneepad (americanfootball set)' => $set . '_e92b',
	'popcorn (americanfootball set)' => $set . '_e92c',
	'calendar (americanfootball set)' => $set . '_e92d',
	'megaphone (americanfootball set)' => $set . '_e92e',
	'light (americanfootball set)' => $set . '_e92f',
	'broken-bone (americanfootball set)' => $set . '_e930',
	'league (americanfootball set)' => $set . '_e931'
);
