<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(
	'smartwatch (tennis set)' => $set . '_e900',
	'tennis-1 (tennis set)' => $set . '_e901',
	'towel (tennis set)' => $set . '_e902',
	'men (tennis set)' => $set . '_e903',
	'megaphone (tennis set)' => $set . '_e904',
	'tennis-ball-4 (tennis set)' => $set . '_e905',
	'versus (tennis set)' => $set . '_e906',
	'tennis-ball-3 (tennis set)' => $set . '_e907',
	'smartphone (tennis set)' => $set . '_e908',
	'championship-1 (tennis set)' => $set . '_e909',
	'tennis-player (tennis set)' => $set . '_e90a',
	'ticket (tennis set)' => $set . '_e90b',
	'scoreboard (tennis set)' => $set . '_e90c',
	'whistle (tennis set)' => $set . '_e90d',
	'trophy-1 (tennis set)' => $set . '_e90e',
	'bounce (tennis set)' => $set . '_e90f',
	'water-bottle (tennis set)' => $set . '_e910',
	'tennis-machine (tennis set)' => $set . '_e911',
	'stopwatch (tennis set)' => $set . '_e912',
	'polo-shirt (tennis set)' => $set . '_e913',
	'star (tennis set)' => $set . '_e914',
	'tennis (tennis set)' => $set . '_e915',
	'sport-bag (tennis set)' => $set . '_e916',
	'racket-1 (tennis set)' => $set . '_e917',
	'socks (tennis set)' => $set . '_e918',
	'championship (tennis set)' => $set . '_e919',
	'visor (tennis set)' => $set . '_e91a',
	'tennis-ball-2 (tennis set)' => $set . '_e91b',
	'net (tennis set)' => $set . '_e91c',
	'tennis-ball-1 (tennis set)' => $set . '_e91d',
	'shoes (tennis set)' => $set . '_e91e',
	'tennis-ball (tennis set)' => $set . '_e91f',
	'tennis-court (tennis set)' => $set . '_e920',
	'medal (tennis set)' => $set . '_e921',
	'podium (tennis set)' => $set . '_e922',
	'trophy (tennis set)' => $set . '_e923',
	'judge-chair (tennis set)' => $set . '_e924',
	'suit (tennis set)' => $set . '_e925',
	'tennis-balls (tennis set)' => $set . '_e926',
	'racket (tennis set)' => $set . '_e927'
);
