<?php

/**
 * 3D Model Carousel Gallery Type (Marquee Mode)
 *
 * @package     MiniGallery
 * @subpackage  3DModelCarousel
 * @since       1.6.0
 */

if (!defined('ABSPATH')) {
    exit;
}

class MGWPP_3D_Model_Carousel
{
    /**
     * Unique gallery type identifier
     */
    const GALLERY_TYPE = '3d_model_carousel';

    /**
     * Supported 3D file formats
     */
    const SUPPORTED_FORMATS = [
        'gltf' => 'model/gltf+json',
        'glb'  => 'model/gltf-binary',
        'obj'  => 'model/obj',
        'fbx'  => 'application/octet-stream'
    ];

    /**
     * Render the 3D model carousel (marquee mode)
     *
     * @param int   $post_id Gallery post ID
     * @param array $images  Array of image/3D model objects
     * @param array $settings Gallery settings
     * @return string HTML output
     */
    public static function render($post_id, $images, $settings = [])
    {
        // Filter to only 3D models
        $models = self::filter_3d_models($images);

        if (empty($models)) {
            return self::render_no_models_message();
        }

        // Get settings with defaults
        $defaults = [
            'marquee_speed'    => 1,        // Pixels per frame
            'rotation_angle'   => 75,       // Degrees
            'rotation_speed'   => 0.005,    // Radians per frame
            'background_color' => '#1a1a1a',
            'pause_on_hover'   => true,
            'show_info_on_hover' => true,
            'max_loaded_models' => 12,       // Memory management
        ];

        $settings = wp_parse_args(
            get_post_meta($post_id, 'mgwpp_3d_settings', true),
            $defaults
        );

        // Enqueue assets
        self::enqueue_assets($settings);

        ob_start();
?>
        <div class="mgwpp-3d-model-marquee"
            data-settings='<?php echo esc_attr(wp_json_encode($settings)); ?>'
            data-post-id="<?php echo esc_attr($post_id); ?>">

            <!-- Grid Container -->
            <div class="mgwpp-3d-grid">
                <!-- Grid items will be generated by JavaScript -->
            </div>

            <!-- Hidden data container for models -->
            <div class="mgwpp-3d-models-data" style="display: none;">
                <?php foreach ($models as $model) : ?>
                    <?php
                    $model_link = get_post_meta($model->ID, '_mgwpp_3d_model_link', true);

                    $model_data = [
                        'id'       => $model->ID,
                        'url'      => wp_get_attachment_url($model->ID),
                        'title'    => get_the_title($model->ID),
                        'caption'  => wp_get_attachment_caption($model->ID),
                        'format'   => self::get_model_format($model->ID),
                        'fileSize' => filesize(get_attached_file($model->ID)),
                        'link'     => $model_link ? esc_url($model_link) : '',
                    ];
                    ?>
                    <div class="mgwpp-3d-model-data"
                        data-model='<?php echo esc_attr(wp_json_encode($model_data)); ?>'>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
<?php
        return ob_get_clean();
    }

    /**
     * Filter 3D models from images array
     */
    private static function filter_3d_models($attachments)
    {
        $models = [];

        foreach ($attachments as $attachment) {
            $mime_type = get_post_mime_type($attachment->ID);

            if (in_array($mime_type, array_values(self::SUPPORTED_FORMATS), true)) {
                $models[] = $attachment;
            }
        }

        return $models;
    }

    /**
     * Get model file format
     */
    private static function get_model_format($attachment_id)
    {
        $file = get_attached_file($attachment_id);
        $ext = pathinfo($file, PATHINFO_EXTENSION);
        return strtolower($ext);
    }

    /**
     * Message when no 3D models found
     */
    private static function render_no_models_message()
    {
        return sprintf(
            '<div class="mgwpp-3d-no-models">%s</div>',
            esc_html__('No 3D models found. Please upload GLTF or GLB files.', 'mini-gallery')
        );
    }

    /**
     * Enqueue required assets
     *
     * Note: Three.js and GLTFLoader are loaded from CDN because:
     * 1. They are large libraries (~600KB+ combined) that would bloat the plugin
     * 2. CDN provides better performance with caching across sites
     * 3. These are industry-standard libraries required for 3D rendering
     * 4. Libraries are bundled locally to comply with WordPress.org guidelines
     */
    private static function enqueue_assets($settings)
    {
        // Three.js - Bundled locally for WordPress.org compliance
        wp_enqueue_script(
            'three-js',
            MG_PLUGIN_URL . '/includes/gallery-types/mgwpp-3d-model-carousel/libs/three.min.js',
            [],
            '0.128.0',
            true
        );

        // GLTF Loader - Bundled locally for WordPress.org compliance
        wp_enqueue_script(
            'three-gltf-loader',
            MG_PLUGIN_URL . '/includes/gallery-types/mgwpp-3d-model-carousel/libs/GLTFLoader.js',
            ['three-js'],
            '0.128.0',
            true
        );

        // DRACO Loader - For compressed models
        wp_enqueue_script(
            'three-draco-loader',
            MG_PLUGIN_URL . '/includes/gallery-types/mgwpp-3d-model-carousel/libs/DRACOLoader.js',
            ['three-js', 'three-gltf-loader'],
            '0.128.0',
            true
        );

        // Our custom CSS
        wp_enqueue_style(
            'mgwpp-3d-model-carousel-styles',
            MG_PLUGIN_URL . '/includes/gallery-types/mgwpp-3d-model-carousel/mgwpp-3d-model-carousel.css',
            [],
            MGWPP_ASSET_VERSION
        );

        // Our custom JS
        wp_enqueue_script(
            'mgwpp-3d-model-carousel-js',
            MG_PLUGIN_URL . '/includes/gallery-types/mgwpp-3d-model-carousel/mgwpp-3d-model-carousel.js',
            ['three-js', 'three-gltf-loader', 'three-draco-loader'],
            MGWPP_ASSET_VERSION,
            true
        );

        // Localize script with settings
        wp_localize_script('mgwpp-3d-model-carousel-js', 'mgwpp_3d_settings', [
            'ajax_url'   => admin_url('admin-ajax.php'),
            'nonce'      => wp_create_nonce('mgwpp_3d_nonce'),
            'draco_path' => 'https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/libs/draco/', // Use CDN for dev stability, or local libs/draco/ if bundled
            'text'       => [
                'loading'     => esc_html__('Loading', 'mini-gallery'),
                'loaded'      => esc_html__('Loaded', 'mini-gallery'),
                'error'       => esc_html__('Error loading model', 'mini-gallery'),
            ],
            'settings'   => $settings,
        ]);
    }

    /**
     * Register 3D MIME types for upload
     */
    public static function register_mime_types($mimes)
    {
        foreach (self::SUPPORTED_FORMATS as $ext => $mime) {
            $mimes[$ext] = $mime;
        }
        return $mimes;
    }



    /**
     * Add custom field to attachment form for model link
     */
    public static function add_attachment_fields($form_fields, $post)
    {
        $mime_type = get_post_mime_type($post->ID);

        // Only show for 3D model formats
        if (in_array($mime_type, array_values(self::SUPPORTED_FORMATS), true)) {
            $model_link = get_post_meta($post->ID, '_mgwpp_3d_model_link', true);

            $form_fields['mgwpp_3d_model_link'] = [
                'label' => __('Model Link URL', 'mini-gallery'),
                'input' => 'text',
                'value' => $model_link,
                'helps' => __('Enter a URL to open when this 3D model is clicked (opens in new tab)', 'mini-gallery'),
            ];
        }

        return $form_fields;
    }

    /**
     * Save attachment custom field
     */
    public static function save_attachment_field($post, $attachment)
    {
        if (isset($attachment['mgwpp_3d_model_link'])) {
            $link = esc_url_raw($attachment['mgwpp_3d_model_link']);
            update_post_meta($post['ID'], '_mgwpp_3d_model_link', $link);
        }

        return $post;
    }
}
