<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

	'tournament (basketball set)' => $set . '_e900',
	'basketball-player (basketball set)' => $set . '_e901',
	'fire (basketball set)' => $set . '_e902',
	'win (basketball set)' => $set . '_e903',
	'basketball-ball (basketball set)' => $set . '_e904',
	'talk (basketball set)' => $set . '_e905',
	'strategy (basketball set)' => $set . '_e906',
	'uniform (basketball set)' => $set . '_e907',
	'team (basketball set)' => $set . '_e908',
	'whistle (basketball set)' => $set . '_e909',
	'website (basketball set)' => $set . '_e90a',
	'search (basketball set)' => $set . '_e90b',
	'shop (basketball set)' => $set . '_e90c',
	'workout (basketball set)' => $set . '_e90d',
	'calendar (basketball set)' => $set . '_e90e',
	'education (basketball set)' => $set . '_e90f',
	'team1 (basketball set)' => $set . '_e910',
	'betting (basketball set)' => $set . '_e911',
	'uniform1 (basketball set)' => $set . '_e912',
	'education1 (basketball set)' => $set . '_e913',
	'skill (basketball set)' => $set . '_e914',
	'basketball-player1 (basketball set)' => $set . '_e915',
	'basket (basketball set)' => $set . '_e916',
	'talk1 (basketball set)' => $set . '_e917',
	'basketball-player2 (basketball set)' => $set . '_e918',
	'rotation (basketball set)' => $set . '_e919',
	'cup (basketball set)' => $set . '_e91a',
	'rings (basketball set)' => $set . '_e91b',
	'badge (basketball set)' => $set . '_e91c',
	'store (basketball set)' => $set . '_e91d',
	'medal (basketball set)' => $set . '_e91e',
	'basket1 (basketball set)' => $set . '_e91f',
	'award (basketball set)' => $set . '_e920',
	'time-out (basketball set)' => $set . '_e921',
	'stand (basketball set)' => $set . '_e922',
	'court (basketball set)' => $set . '_e923',
	'steaming (basketball set)' => $set . '_e924',
	'strategy1 (basketball set)' => $set . '_e925',
	'basket2 (basketball set)' => $set . '_e926',
	'location (basketball set)' => $set . '_e927',
	'badge1 (basketball set)' => $set . '_e928',
	'ticket (basketball set)' => $set . '_e929',
	'basketball-ball1 (basketball set)' => $set . '_e92a',
	'speed (basketball set)' => $set . '_e92b',
	'sneakers (basketball set)' => $set . '_e92c',
	'basket3 (basketball set)' => $set . '_e92d',
	'locker-room (basketball set)' => $set . '_e92e',
	'time (basketball set)' => $set . '_e92f',
	'streaming (basketball set)' => $set . '_e930',
	'emblem (basketball set)' => $set . '_e931'
);
